### ISSUE TITLE
Informace o cílovém projektu

### ISSUE THREAD

**Issue by padak** [keboola/wr-storage#17]
Je potřeba při uložení tokenu uložit informaci o cílovém projektu a ID tokenu, aby šlo poznat kam se data posílají.

**Comment by odinuv** [comment]
duplicate of https://github.com/keboola/kbc-ui/issues/1959

**Comment by odinuv** [comment]
pridat do logu

**Comment by odinuv** [comment]
fixed in 5bf81db303ef1b2cfc6cdeb60b30682a46f42b77
