### ISSUE TITLE
Error message typos

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/wr-storage#4]
`Processing table 6colpk.csvInvalid table name:Only alphanumeric characters dash and underscores are allowed in table name.`

**Comment by odinuv** [comment]
odradkovani je vyreseny tady https://github.com/keboola/wr-storage/commit/7605be526e9592f2ce81d6b904844de187bd18bf#diff-c694a29ec41709ca1a5f5e8a29f6467eL29
a mezera chybi tady https://github.com/keboola/connection/blob/38464f3517c9fb2e4d12e75675badc5238ff8c39/application/modules/storage/services/TableCreate.php#L242 :)

**Comment by ondrejhlavacek** [comment]
super! posílám PR na connection :-)
