### ISSUE TITLE
sync actions

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/wr-storage#7]
- zvalidování tokenu
- načtení názvu cílového bucketu do UI (chceme to? může to bejt leak...)

**Comment by odinuv** [comment]
jak by to mohl byt leak?
mas token = mas autorizaci, ne? 

to zvalidovani by teda melo asi vracet i project name, ne?

**Comment by ondrejhlavacek** [comment]
Tak třebas dostal token, ale autor nechce vědět, do jakýho projektu a jakýho bucketu to sypeš.

**Comment by odinuv** [comment]
no tak zrovna padak psal, ze by to videt chtel a me to prijde taky celkem logicky mi moznost overit, kam to zapisujes, to by ti taky mohl nekdo dat token do svyho soukromyho projektu

**Comment by ondrejhlavacek** [comment]
taky pravda, proto jsem tam původně dával otazník :-)
