### ISSUE TITLE
incrementals

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/wr-storage#8]
inkrementální load do storage, bude to přes `procesor-create-manifest`, nebo se to musí zadrátovat do komponety?

**Comment by odinuv** [comment]
musi se to zadaratovat a tady predat incremental https://github.com/keboola/wr-storage/blob/master/src/Component.php#L35

nevidim, zpusob jak by tu mohl byt procesor uzitecnej

**Comment by ondrejhlavacek** [comment]
jo, to mi nedošlo, procesory jsou na tohle vlastně k ničemu, bude to muset bejt drát :-)
